name       : plasma-disks
version    : 5.21.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/plasma-disks-5.21.2.tar.xz : eee1bd40d72f62710aefa7c2909a4b900b1b1a9f47fbf7e48a1b0ee90654f413
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-3.0.only
component  : system.utils
summary    : Monitors S.M.A.R.T. capable devices for imminent failure
description: |
    Monitors S.M.A.R.T. capable devices for imminent failure
optimize   : lto
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
    - smartmontools-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
