name       : plasma-disks
version    : 5.23.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.2/plasma-disks-5.23.2.tar.xz : 7c8e8fde93f0ba4d860f7c4b814ac6daccceeae6ec38b1ec095b49b2cb081b5e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-3.0-only
    - LGPL-3.0.only
component  : system.utils
summary    : Monitors S.M.A.R.T. capable devices for imminent failure
description: |
    Monitors S.M.A.R.T. capable devices for imminent failure
optimize   : lto
builddeps  :
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - knotifications-devel
    - kpackage-devel
    - smartmontools-devel
rundeps    :
    - smartmontools
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
